server:
  port: 8080
  servlet:
    context-path: /smart-api

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:9443/oauth2/token
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: debug
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    reactor.netty.http.client: DEBUG